### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by atitpatel** [genexu/react-native-pie-chart#1]
Are you planning to support Android as well? Your iOS implementation works perfect for me, but require Android support as well for my project. Thanks in advance.

**Comment by genexu** [comment]
Yes, i have plan to fix it, but unfortunately it will not complete in the near future. Because i'm fulfilling my mandatory military service for my country now, it will take nearly a year. I will fix it soon when i have free time, thanks for your comment.

**Comment by taoliu427** [comment]
I have the same problem,can you fix it when you have free time. Thanks in advance.

**Comment by taoliu427** [comment]
Can you tell me where to change in Android ? I desperately need your help. Thanks

**Comment by genexu** [comment]
I only have few times can use internet every day, so sad...

BTW,This issue is coming from ART lib, you can find this issue in other module too (like below)
https://github.com/tomauty/react-native-chart/issues/85

you can follow this clue to fix this problem.

**Comment by taoliu427** [comment]
Ok, Thank you for your answer, I'll go back and check it out.

**Comment by nihgwu** [comment]
I published a PieChart component works on both iOS and Android perfectly
https://github.com/nihgwu/react-native-pie

**Comment by genexu** [comment]
@nihgwu Thanks for your comment, i follow some project to fix this issue (include your), and thanks again for your contribution.

Here is some projects i follow
https://github.com/facebook/react-native/blob/master/Libraries/ART/ARTSerializablePath.js
https://github.com/bgryszko/react-native-circular-progress/blob/master/src/CircularProgress.js
https://github.com/nihgwu/react-native-pie
Also Doc
https://github.com/react-native-china/react-native-ART-doc/blob/master/doc.md

I only add few code to handle android issue, and keep my original code about ios part, ''maybe'' ART author will fix android issue someday, than we can use it origin method to draw.
