### ISSUE TITLE
Android pie is broken

### ISSUE THREAD

**Issue by eugenek239** [genexu/react-native-pie-chart#14]
It is better not to make it public until both platforms are supported.
![screen shot 2017-10-04 at 11 31 06 am](https://user-images.githubusercontent.com/32399853/31192983-9cc62dc2-a8f7-11e7-9f75-38afc6e11435.png)

**Comment by genexu** [comment]
@eugenek239 Greeting and thanks for your reporting.

This is  dependency bug from React Native, and there is relation issue follow https://github.com/genexu/react-native-pie-chart/issues/10

In addition, i do not have too much time on this project, but i will keep tracking the issue, welcome any PR and feedback.
