### ISSUE TITLE
Large data rendering issue

### ISSUE THREAD

**Issue by yenduttjain** [genexu/react-native-pie-chart#15]
When I have large data the chart messes up. Refer attached screenshot. Solution is appreciated.
![piechart](https://user-images.githubusercontent.com/10963773/32987973-c43d33c2-cd1f-11e7-810d-d44dbda59120.PNG)

**Comment by genexu** [comment]
Thanks for report, could u give me clear chart and data series help me to determine the problem?

And this package doesn't provide label feature, so if you mean your description label messes up, it is not related with this library.

**Comment by genexu** [comment]
There doesn't have further information about this issue, so i will close this issue.
