### ISSUE TITLE
No Component Found For View With Name ARTShape.

### ISSUE THREAD

**Issue by thecodecafe** [genexu/react-native-pie-chart#16]
In your installation instruction it says the second step says link art , do you mean to run `react-native link`? if so then I think you should state that, but anyways I've ran `react-native link` and got an error, No component found for view with name ARTShape.

**Comment by genexu** [comment]
@thecodecafe Hi, ARTShape is ReactNatvie ART libs component, so you have to open the ART project inside the React Native structure and add libART.a to your workspace.

Ref: 
**"If the library has native code, there must be a .xcodeproj file inside the folder. Drag this file to your project on Xcode (usually under the Libraries group on Xcode);"**

https://facebook.github.io/react-native/docs/linking-libraries-ios.html#manual-linking
https://github.com/facebook/react-native/tree/master/Libraries/ART/ART.xcodeproj

Having a nice day.
