### ISSUE TITLE
Pie Chart Shape issue in Android only

### ISSUE THREAD

**Issue by nadeem362** [genexu/react-native-pie-chart#19]
Pie Chart get scattered in the given area. It doesn't draw a complete circle.
![screen shot 2018-05-29 at 3 16 10 pm](https://user-images.githubusercontent.com/37949470/40653019-5471cfa6-6353-11e8-9eec-8212ae450b4d.png)

**Comment by aidin36** [comment]
I'm closing this because it's quite old. I don't see this issue with the latest version.
Feel free to open this again, or create a new issue.
