### ISSUE TITLE
what units for data series

### ISSUE THREAD

**Issue by indefinitelee** [genexu/react-native-pie-chart#2]
Hi, can you tell me what units the series values are in; is it radians? 
What would values be for a 50/50 pie chart for example?

Thanks for the help

**Comment by genexu** [comment]
There was no limited what units you use, it will auto calculate to percentage and generate pie chart.
If you want output 50/50(I don't really sure what you mean, you mean half half?) pie chart, just give it [50, 50].

**Comment by indefinitelee** [comment]
thanks, that seems obvious now.
