### ISSUE TITLE
Android: Chart is disappeared when screen is locked and opened back.

### ISSUE THREAD

**Issue by nithinyell** [genexu/react-native-pie-chart#23]
### Steps to reproduce:

- Keep the app in foreground with chart displaying
- Lock the device
- Unlock and see the empty screen, Chart is not visible

**Comment by giantslogik** [comment]
https://github.com/facebook/react-native/issues/17565

**Comment by aidin36** [comment]
I'm closing this one. Thanks @giantslogik for pointing out the `react-native` bug.
