### ISSUE TITLE
ART has been removed from react native

### ISSUE THREAD

**Issue by ighotouch** [genexu/react-native-pie-chart#24]
<img width="353" alt="Screenshot 2020-04-05 12 37 31" src="https://user-images.githubusercontent.com/3287439/78473658-4f45bb80-773a-11ea-884d-f2179be197ff.png">

**Comment by sarmad1995** [comment]
Use my fork until it resolves.
https://github.com/sarmad1995/react-native-pie-chart
I have also added readme for art installation (Just added a link)

**Comment by aidin36** [comment]
Thanks for the report. It's fixed in the new release. `2.0.1`.
