### ISSUE TITLE
error & solution: no component found for view with name ARTShape

### ISSUE THREAD

**Issue by daheeahn** [genexu/react-native-pie-chart#26]
react-native: 0.61.5
react-native-pie-chart: 1.0.13

I installed this library and I faced "no component found for view with name ARTShape" error.
So I found solution. 
(https://github.com/oblador/react-native-progress/issues/127#issuecomment-530892106)

`yarn add @react-native-community/art`

Please write to the REAME that you also need to install this

**Comment by aidin36** [comment]
Thanks for the report. I explained this in the README file.
