### ISSUE TITLE
Would like to become the maintainer

### ISSUE THREAD

**Issue by aidin36** [genexu/react-native-pie-chart#28]
Hi @genexu,

I would like to become the maintainer of this package. My company (https://github.com/movio/) uses this package in one of its apps. It's a nice little package that does the job and we don't need to add some large dependencies to our app just to draw a pie chart.

You did a great job writing this package. I understand you don't have time anymore to maintain this. So I decided to step up and take the responsibility, so this useful package can live on.

Please let me know what do you think.

**Comment by genexu** [comment]
Hello @aidin36 

You can feel free to fork this repository and use in any application when this repo was no longer maintained, nice to know that you are like this package.

Best regards.

**Comment by aidin36** [comment]
That would be my last option (:

This repo and the package on npmjs already gained some reputation. There are a couple of blog posts and guides that link this package, and it has 68 stars. It would be nicer to bring this back to life rather than creating a new repo and trying to gain all the reputation again.

**Comment by genexu** [comment]
Understand, I already invite you as collaborator, tell me if you need anything support, thanks for your helping.

**Comment by aidin36** [comment]
Awesome. Thanks!

**Comment by aidin-gh** [comment]
@genexu Can you please add me as a maintainer in the `npmjs.com`? So I can publish new versions? My user is `aidin36`.
Thanks.

**Comment by genexu** [comment]
@aidin36 Sorry for the late response, i am quite busy recently, i just add you as collaborator, thank you.

**Comment by aidin36** [comment]
No worries. Thank you! Hopefully I won't bother you again about this package (:
