### ISSUE TITLE
Invariant Violation: ART has been removed from React Native. It can now be installed and imported from '@react-native-community/art' instead of 'react-native'

### ISSUE THREAD

**Issue by yogendrajs** [genexu/react-native-pie-chart#29]
```
"react-native": "0.64.2"
"react-native-pie-chart": "^1.0.13"
"@react-native-community/art": "^1.2.0"
```
I've recently updated my RN version along with the RNPC version to the listed above, but keep getting this error. Although, have seen there's no need to link `@react-native-community/art` manually. I did hope that it would work out of the box but didn't. 
Any possible workaround for this would be of great help. 
Thanks!

**Comment by aidin36** [comment]
Version one is not compatible with newer react native. Can you please upgrade to the latest version? `2.0.2`?
The only change you need to make is changing `chart_wh` to `widthAndHeight`, as described in the README file.

**Comment by yogendrajs** [comment]
Hey @aidin36, thanks, updated it to 2.0.2, but still getting the following error-
```
Invariant Violation: [1793,"ARTShape",1,{"fill":[0,0.5137254901960784,0.7294117647058823,0.2549019607843137,1],"opacity":1,"stroke":null,"strokeCap":1,"strokeDash":null,"strokeJoin":1,"strokeWidth":1,"transform":[1,0,0,1,0,0],"d":[0,"<<NaN>>","<<NaN>>",2,"<<NaN>>","<<NaN>>",2,"<<NaN>>","<<NaN>>"]}] is not usable as a native method argument
```

**Comment by aidin36** [comment]
Can you please post your code here? How do you create the PieChart component?

My guess is you still pass `chart_wh` instead of `widthAndHeight`.

**Comment by yogendrajs** [comment]
> Can you please post your code here? How do you create the PieChart component?
> 
> My guess is you still pass `chart_wh` instead of `widthAndHeight`.

Hey @aidin36, you guessed it right. After making this change, it's working perfectly fine. Thanks for your time. 
Closing this here :)

**Comment by aidin36** [comment]
Happy to help (:
