### ISSUE TITLE
 Error: Unable to resolve module @react-native-community/art

### ISSUE THREAD

**Issue by dream-topdev** [genexu/react-native-pie-chart#32]
After I install react-native-pi-chart via 'yarn add react-native-pie-chart', the developer console shows error as belows.

error: Error: Unable to resolve module @react-native-community/art from D:\working\CovidTracker\node_modules\react-native-pie-chart\dist\Pie.js: @react-native-community/art could not be found within the project or in these directories:
  node_modules\react-native-pie-chart\node_modules
  node_modules

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*

Is there any good way to tackle this issue?

**Comment by gaurav0497** [comment]
Try npm i @react-native-community/art.

**Comment by andordavoti** [comment]
Please refer to the documentation in the readme for the package: "You need to have react, react-native and @react-native-community/art as your app's dependencies."

**Comment by aidin36** [comment]
Thanks guys for helping with answering this. Closing now.
