### ISSUE TITLE
Error in rendering pie chart (angle greater than 360)

### ISSUE THREAD

**Issue by acapellacci** [genexu/react-native-pie-chart#33]
With this series

[789669, 530000, 40149, 3236, 16358, 26] 

in index.tsx, the expression 

previous[previous.length - 1] + Math.round((360 * current) / sum)

returns an angle greater than 360. 

Math.round should be changed in Math.floor

**Comment by aidin36** [comment]
Thanks for catching this @acapellacci . Are you keen to send a PR? To keep the credit? Otherwise, I can fix it myself.

**Comment by acapellacci** [comment]
> Thanks for catching this @acapellacci . Are you keen to send a PR? To keep the credit? Otherwise, I can fix it myself.

@aidin36 Fix it yourself, please.

**Comment by andordavoti** [comment]
can you submit a new release with this fix? also ran into this issue, this commit seems to solve my case

**Comment by acapellacci** [comment]
> can you submit a new release with this fix? also ran into this issue, this commit seems to solve my case

unfortunately I do not have writing privileges. The owner should do that.

**Comment by aidin36** [comment]
Sorry for the long delay.
It's now published in `2.1.0` version.
