### ISSUE TITLE
Show warning after Pie style prop update

### ISSUE THREAD

**Issue by genexu** [genexu/react-native-pie-chart#5]
@mithunm93 
I'm doing further testing today, use newest version react-native, and it will show warning after Pie style prop update, did you have same problem?

In addition, can you show me propType errors you say at original version? I don't get any error at original version, so i want to see what error it is.(original version mean the version before merge you PR)

![screen shot 2017-04-22 at 8 40 01 pm](https://cloud.githubusercontent.com/assets/20200209/25304579/bb3f608e-279c-11e7-9853-2d6591fa3841.png)

**Comment by genexu** [comment]
I just fix this warning in new commit https://github.com/genexu/react-native-pie-chart/commit/d37f2a4921834b8d52647a4c933ed26ad1d15776

The problem is View.propTypes.style not support isRequired method, and style should not be required also, thanks you a lot :)

**Comment by mithunm93** [comment]
@genexu thank you so much! I was actually creating another PR for that! I think i accidentally made a PR to my own fork :( . Sorry for all the confusion and thank you for helping me with this!

**Comment by mithunm93** [comment]
https://github.com/mithunm93/react-native-pie-chart/pull/1/commits/2e25446d83f52cb033455a4953ddcf5ce2e5b8db haha

**Comment by genexu** [comment]
No worries, it's ok :)
