### ISSUE TITLE
View.propTypes warnings

### ISSUE THREAD

**Issue by fdiep** [genexu/react-native-pie-chart#6]
Looks like View.propTypes will be deprecated in future releases of ReactNative.

"Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead"

**Comment by genexu** [comment]
Yes, this warning start showing on RN 0.44 version, i will implement this feature soon, thanks for your report.

**Comment by genexu** [comment]
Update complete and new version is published, please update your package dependency.
