### ISSUE TITLE
Disappearing chart on screen off.

### ISSUE THREAD

**Issue by sidbans** [genexu/react-native-pie-chart#7]
Hey,

So I'm having a strange issue with the pie chart disappearing if the screen is turned off and turned back on. I could not figure out a way to re-render the chart in such a scenario. What's going on here?

Thanks!

**Comment by genexu** [comment]
Greeting,

I just testing on some android device, but there have no situation like that, can you give me more detail about this issue (package dependencies, device info...etc.)?

Thanks for your report.

**Comment by sidbans** [comment]
Hey,

Using Nougat (7.1.2) on my own device.

Everything renders okay like so:
![img1](http://i.imgur.com/fgKCuYK.png)

After turning the screen off, and then back on:
![img2](http://i.imgur.com/7wmC627.png)

Reloading the application makes it show up again.

**Comment by genexu** [comment]
Did you use other device to test? here is my solution to checking what is problem.

Use react native AppState api to control and check app status, you can also use this api to handle this issue, re-render component  when screen turn on, in addition, use console log to confirm render function work normally when device screen turn off and on.

By the way, might you give me some console log to help me understand this issue, thanks a lot :)

AppState
https://facebook.github.io/react-native/docs/appstate.html

**Comment by genexu** [comment]
Because of there are no further comment, i decided to close this issue, if have any question or similar problem, plz give me a notice.

**Comment by gargankita** [comment]
Hi genexu, I am having a similar problem. The pie chart disappears after the screen is off.
