### ISSUE TITLE
Wedge.render(): A valid Rect element (or null) must be returned

### ISSUE THREAD

**Issue by x-bingxin** [genexu/react-native-pie-chart#9]
![image](https://user-images.githubusercontent.com/9410789/26914254-d41178e2-4c52-11e7-8772-423ba645e3f8.png)

Hi, I got this issue while I tried to render a piechart, and the `series` is `[0, 100]` or `[100, 0]`.
I found the code in wedge.js file like below:
![image](https://user-images.githubusercontent.com/9410789/26914307-23f5130a-4c53-11e7-8868-b9c8c2e8ca88.png)

It's wired to return nothing in render method.

**Comment by x-bingxin** [comment]
The version I used in my project is 1.0.9, after upgrade version to 1.0.11, the issue has gone, thank you, I will close the issue.

**Comment by huangxiaohao** [comment]
@Bing-Xia hi, I have the same issue with you.
But when I upgrade , the version was 1.0.12 , and my RN version is 0.41.2, it doesn't work.
so I want to know what your RN version is ?  and I tried to use `$ npm install react-native-pie-chart@1.0.11 --save` ,but it doesn't work too.
Thank you!!!!!

**Comment by huangxiaohao** [comment]
hi,
I think I've solved the problem, upgrade version to 1.0.11, the issue has gone, thank you!!!
